apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: vaideesh30/mytodolistappaks:frontend-1.14 # Replace with your image
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_URL
          value: "http://backend-service:5000"
